notes on traps and locks

diff --git a/bashNotes b/bashNotes
--- a/bashNotes
+++ b/bashNotes
@@ -85,6 +85,34 @@ export DIR1=whatever
 export DIR2=whatever2
 find $DIR1 $DIR2 -type f -exec sha1sum '{}' \+ | sort | uniq -c --check-chars 40 | egrep '^ *1 ' | cut -c 51-
 
+Running sth at exit no-matter-what
+----------------------------------
+
+function my_function {
+  rm whatever;
+}
+
+trap my_function INT TERM EXIT HUP
+
+Do sth in a lock
+-----------------
+
+lockfile=/var/tmp/mylock
+
+if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; then
+
+        trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
+
+        # do stuff here
+
+        # clean up after yourself, and release your trap
+        rm -f "$lockfile"
+        trap - INT TERM EXIT
+else
+        echo "Lock Exists: $lockfile owned by $(cat $lockfile)"
+fi
+
+
 Argument referencing
 --------------------
 
